### ISSUE TITLE
High-fi UI/UX design for the unresolved filtering feature.

### ISSUE THREAD

**Issue by smithlauren910** [CMU-313/fall23-nodebb-tech-tartans#6]

**Comment by Adeline09** [comment]
Estimated effort: 1 hour per day, 2 days to have an interface
Dependencies: none
Acceptance criteria: have other group members test this feature by assessing the aesthetics and consistency with other tabs, and have them go through the process demonstrated in the prototype

**Comment by Adeline09** [comment]
High-fi interface prototype for the unresolved filtering webpage is attached below. Note that creating an unresolved filtering webpage is a stretch goal. It would be proceeded after successfully implementing an 'Unresolved Topics' filter in the Unread webpage.



![Image](https://github.com/CMU-313/fall23-nodebb-tech-tartans/assets/102492884/9b20f5f5-2dfd-4ca8-b0fb-de4f2c7a6ab4)
